// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoYIXKqkKHwYHRXizGV0GGcVekecE5b6E',
    appId: '1:721039495119:web:dc5fdb5e346fef43058cba',
    messagingSenderId: '721039495119',
    projectId: 'dapurnusarasa',
    authDomain: 'dapurnusarasa.firebaseapp.com',
    storageBucket: 'dapurnusarasa.firebasestorage.app',
    measurementId: 'G-K9KTDX28GR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYH2pU2LXPTR1DBkTe5zC49k4zWr4CYHw',
    appId: '1:721039495119:android:e7f2e5e0f3c1e31f058cba',
    messagingSenderId: '721039495119',
    projectId: 'dapurnusarasa',
    storageBucket: 'dapurnusarasa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKRAWXPFWrBkUJ-X5NlSIsLjFN0sgIZHI',
    appId: '1:721039495119:ios:4e005c393c2d6599058cba',
    messagingSenderId: '721039495119',
    projectId: 'dapurnusarasa',
    storageBucket: 'dapurnusarasa.firebasestorage.app',
    iosBundleId: 'com.example.dapoerNusantara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKRAWXPFWrBkUJ-X5NlSIsLjFN0sgIZHI',
    appId: '1:721039495119:ios:4e005c393c2d6599058cba',
    messagingSenderId: '721039495119',
    projectId: 'dapurnusarasa',
    storageBucket: 'dapurnusarasa.firebasestorage.app',
    iosBundleId: 'com.example.dapoerNusantara',
  );
}
